# roles/kubernetes/tasks/main.yml
---
- name: Add Kubernetes GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: Install Kubernetes components
  apt:
    name:
      - "kubelet={{ k8s_version }}.*"
      - "kubeadm={{ k8s_version }}.*"
      - "kubectl={{ k8s_version }}.*"
    state: present
    update_cache: yes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ pod_network_cidr }}
    --service-cidr={{ service_cidr }}
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
  register: kubeadm_init
  changed_when: kubeadm_init.rc == 0
  failed_when: kubeadm_init.rc != 0 and "already exists" not in kubeadm_init.stderr

- name: Create .kube directory
  file:
    path: "/home/{{ ansible_user | default(ansible_env.USER) }}/.kube"
    state: directory
    owner: "{{ ansible_user | default(ansible_env.USER) }}"
    group: "{{ ansible_user | default(ansible_env.USER) }}"
    mode: '0755'

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user | default(ansible_env.USER) }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user | default(ansible_env.USER) }}"
    group: "{{ ansible_user | default(ansible_env.USER) }}"
    mode: '0644'

- name: Remove master taint (single node cluster)
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  environment:
    KUBECONFIG: "/home/{{ ansible_user | default(ansible_env.USER) }}/.kube/config"
  ignore_errors: yes

- name: Install Flannel CNI
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  environment:
    KUBECONFIG: "/home/{{ ansible_user | default(ansible_env.USER) }}/.kube/config"